package gov.dostxii.springmvc.model;

import java.io.Serializable;

public enum PostSubCat implements Serializable{

	RECRUITMENT_GOVERNANCE ("RECRUITMENT_GOVERNANCE"),
	RECRUITMENT_PLANNING ("RECRUITMENT_PLANNING"),
	RECRUITMENT_SOURCING ("RECRUITMENT_SOURCING"),
	RECRUITMENT_SELECTING ("RECRUITMENT_SELECTING"),
	
	DEVELOPMENT_GOVERNANCE ("DEVELOPMENT_GOVERNANCE"),
	DEVELOPMENT_PLANNING ("DEVELOPMENT_PLANNING"),
	DEVELOPMENT_EXECUTION ("DEVELOPMENT_EXECUTION"),	

	PERFORMANCE_GOVERNANCE ("PERFORMANCE_GOVERNANCE"),
	PERFORMANCE_PLANNING ("PERFORMANCE_PLANNING"),
	PERFORMANCE_REVIEW ("PERFORMANCE_REVIEW"),
	PERFORMANCE_DEVELOPMENT ("PERFORMANCE_DEVELOPMENT"),
	
	RECOGNITION_GOVERNANCE ("RECOGNITION_GOVERNANCE"),
	RECOGNITION_PLANNING ("RECOGNITION_PLANNING"),
	RECOGNITION_IMPLEMENTATION ("RECOGNITION_IMPLEMENTATION");
	
	String str;
	
	private PostSubCat(String str){
		this.str = str;
	}

	public String getStr() {
		return str;
	}

	public void setStr(String str) {
		this.str = str;
	}


	

	
}
